JRUBY-2894: When spec runs fail, Ant is not terminating with a failure message.
* The reason why mspec invocation didn't return failed status is due to
  JRuby launcher bash script overwriting the exit status when -J-ea was set.

* Also, make Ant run RubySpecs in all three modes even if some of them
  fail, and then return the combined result.

git-svn-id: http://svn.codehaus.org/jruby/trunk/jruby@7375 961051c9-f516-0410-bf72-c9f7e237a7b7

diff --git a/bin/jruby b/bin/jruby
--- a/bin/jruby
+++ b/bin/jruby
@@ -215,11 +215,15 @@ if [ "$VERIFY_JRUBY" != "" ]; then
     "-Djruby.shell=$JRUBY_SHELL" \
     org.jruby.Main $JRUBY_OPTS "$@"
 
+  # Record the exit status immediately, or it will be overridden.
+  JRUBY_STATUS=$?
+
   if [ "$PROFILE_ARGS" != "" ]; then
       echo "Profiling results:"
-
       cat profile.txt
   fi
+
+  exit $JRUBY_STATUS
 else
   exec "$JAVA_CMD" $JAVA_OPTS "${java_args[@]}" -Xbootclasspath/a:"$JRUBY_CP" -classpath "$CP$CP_DELIMETER$CLASSPATH" \
     "-Djruby.home=$JRUBY_HOME" \
@@ -227,3 +231,6 @@ else
     "-Djruby.shell=$JRUBY_SHELL" \
     org.jruby.Main $JRUBY_OPTS "$@"
 fi
+
+# Be careful adding code down here, you might override the exit
+# status of the jruby invocation.
